name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Lint and Test
    #   run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build --build-arg GITHUB_SECRET=${{ secrets.GITHUB_SECRET }} --build-arg PORT=${{ vars.PORT }} -t ${{ secrets.DOCKER_USERNAME }}/whale-k8s-webhook-server:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/whale-k8s-webhook-server:latest